FROM golang:1.25

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

# Install air for hot-reloading
RUN go install github.com/air-verse/air@latest

COPY . .

# Use air to run the application
CMD [ "air" ]